"""tender subscriptions, seen, notifications (#37)

Revision ID: 0ab70d27868b
Revises: b1f4a2c7d9e0
Create Date: 2026-07-12 20:13:28.914413
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0ab70d27868b'
down_revision: Union[str, None] = 'b1f4a2c7d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_role', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_recipient_role'), 'notifications', ['recipient_role'], unique=False)
    op.create_table('tender_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('customer', sa.String(length=200), nullable=True),
    sa.Column('recipient_roles', sa.Text(), nullable=False),
    sa.Column('active', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tender_subscriptions'))
    )
    op.create_table('tender_seen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('reg_number', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['tender_subscriptions.id'], name=op.f('fk_tender_seen_subscription_id_tender_subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tender_seen'))
    )
    op.create_index(op.f('ix_tender_seen_subscription_id'), 'tender_seen', ['subscription_id'], unique=False)
    op.create_index('ix_tender_seen_uniq', 'tender_seen', ['subscription_id', 'reg_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tender_seen_uniq', table_name='tender_seen')
    op.drop_index(op.f('ix_tender_seen_subscription_id'), table_name='tender_seen')
    op.drop_table('tender_seen')
    op.drop_table('tender_subscriptions')
    op.drop_index(op.f('ix_notifications_recipient_role'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
