"""user token_version for revocation (#4)

Revision ID: fececcffeb78
Revises: 0ab70d27868b
Create Date: 2026-07-14 12:34:14.037374
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fececcffeb78'
down_revision: Union[str, None] = '0ab70d27868b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
